-- CleanUI mod integration for inventory item name coloring
-- Hooks into CleanUI_getItemNameColor() to return tier colors
-- Uses ISInventoryItem.renderItemIcon() hook to set item context before getItemNameColor is called
--
-- NOTE TO CLEANUI AUTHOR:
-- It would be much better if CleanUI_getItemNameColor() could accept an item parameter,
-- e.g. CleanUI_getItemNameColor(item), instead of requiring mods to use workarounds like
-- hooking into renderItemIcon() to set a global context variable. This would make the
-- API more reliable and easier to use for modders.

--require "ZItemTiers/core"
--
---- Check if CleanUI mod is active
--if not CleanUI_getItemNameColor then return end
--
--zbHook({
--    _G = {
--        CleanUI_getItemNameColor = function(orig, ...)
--            -- Get the current item from context (set by isUnwanted hook)
--            local currentItem = ZItemTiers._zit_currentItem
--
--            if currentItem then
--                -- Check if item has tier
--                local tier = ZItemTiers.GetItemTierKey(currentItem)
--
--                if tier then
--                    local tierData = ZItemTiers.Tiers[tier]
--                    local color = tierData.color
--
--                    -- Return tier color (only if not Common, since Common is white like default)
--                    if tier ~= "Common" then
--                        return {r = color.r, g = color.g, b = color.b}
--                    end
--                end
--            end
--
--            -- Fall back to original CleanUI color
--            return orig(...)
--        end,
--    },
--})
